### ISSUE TITLE
Indentation tabs don't respect tab size specified in Notepad++ settings

### ISSUE THREAD

**Issue by ExE-Boss** [dail8859/ElasticTabstops#8]
The size of indentation tabs should be what is defined in:
Settings > Preferences > Language > Tab Settings > Tab size

**Comment by dail8859** [comment]
Can you provide more details (e.g. screenshots, versions, etc)? It works fine for me.

![4](https://cloud.githubusercontent.com/assets/3694843/25403010/c74fe9e2-29c8-11e7-9c63-b6b48be991e1.png)

---

![8](https://cloud.githubusercontent.com/assets/3694843/25403015/ca322a12-29c8-11e7-9d12-48157ec18ff9.png)

**Comment by ExE-Boss** [comment]
It seems to only happen when I change fonts.
Plugin version: 1.1
Notepad++ version: 7.3.3

### Before:
![before switching to a different font](https://cloud.githubusercontent.com/assets/3889017/25403546/fc62dd36-29fc-11e7-8c4f-de2ae80f0359.png)

### After:
![after switching to a different font](https://cloud.githubusercontent.com/assets/3889017/25403558/fddf0fa4-29fc-11e7-98a5-0b04f05c2e6f.png)

**Comment by dail8859** [comment]
Can you tell me what you changed exactly and to which font so I can try to reproduce it?

**Comment by ExE-Boss** [comment]
It happens when changing to any font where there is a visible difference in the space width
(the ones in the screenshots are [Consolas](https://www.microsoft.com/typography/Fonts/family.aspx?FID=300) and [Input](http://input.fontbureau.com) respectively).

The setting is Settings > Style Configurator > Global Styles > Default Style > Font
Note that I have been able to reproduce this only sometimes.

**Comment by dail8859** [comment]
This should fix it but I'd like you to verify it works. Download the zip below and extract. Copy the ElasticTabstops.dll file over the current one you have, most likely located in `C:\Program Files (x86)\Notepad++\plugins`

[ElasticTabstops.zip](https://github.com/dail8859/ElasticTabstops/files/956375/ElasticTabstops.zip)

**Comment by ExE-Boss** [comment]
It still doesn't work (it only changes the indentation tab size when changing the open document)

**Comment by dail8859** [comment]
Would it be possible to zip up a small example text file and the exact font you are using (as it might be a customized version if Input)? I'm not sure if it is just any non-monospaced font or something specific to the Input font.

**Comment by ExE-Boss** [comment]
It happens with every arbitrary font for me (not just Input)

**Comment by dail8859** [comment]
> It happens with every arbitrary font for me

Ok good to know. Using the DLL file from above...I set my default font to Times New Roman and this is what it looks like for a tab width of 8

![capture](https://cloud.githubusercontent.com/assets/3694843/25438005/2cca5b0c-2a66-11e7-8ace-87f4bb48a9f3.PNG)


Also to be clear I should state that if you make any changes to the style settings or tab sizes you should switch to another file and then switch back to it so it forces a recalculation of the tabstops. (Notepad++ doesn't notify plugins of those types of changes to style settings.)

**Comment by ExE-Boss** [comment]
> Notepad++ doesn't notify plugins of those types of changes to style settings.

Looks like it's time to file a bug for Notepad++ to add that feature.

I discovered that it is needed to switch between open files on my own in a [previous comment](https://github.com/dail8859/ElasticTabstops/issues/8#issuecomment-297154254).

**Comment by dail8859** [comment]
So does that mean it is working (aside from the N++ issue) for you or is there still something I'm missing?

**Comment by ExE-Boss** [comment]
It is working now, minus the need to switch between open files when changing fonts or tab size.

**Comment by dail8859** [comment]
Ok, great. Thanks for the report.
